### ISSUE TITLE
Comman not found

### ISSUE THREAD

**Issue by ryangp** [AGENT404TRD/BOXVIDRA-EMULATOR-BETA-#32]
![Screenshot_20240907_070859_com termux](https://github.com/user-attachments/assets/2f438442-6194-4eaa-bbd4-05292277bccd)
`curl -s -o ~/x https://raw.githubusercontent.com/AGENT404TRD/BOXVIDRA-PROJECT/boxvidra/install-native && . ~/x`

using the above command in Termux, then it return 

`No command 404: found, did you mean:
 Command 2048 in package 2048-c`

**Comment by ryangp** [comment]
I was able to figure it out using this command 
`curl -s -o ~/x https://raw.githubusercontent.com/AGENT404TRD/BOXVIDRA-PROJECT/boxvidra/Scripts/Native/install-native && . ~/x`

**Comment by HasanMH786** [comment]
MD Hasan:
please boxvidra install in termux type boxvidra but show command not found

from UAE please solve this problem

please please solve this
