### ISSUE TITLE
BOXVIDRA THEMES missing Windows 11

### ISSUE THREAD

**Issue by ryangp** [AGENT404TRD/BOXVIDRA-EMULATOR-BETA-#33]
![Screenshot_20240907_095253](https://github.com/user-attachments/assets/c2f501fd-deae-4f71-9c6b-6218b27b2650)

The windows 11 themes are missing.

**Comment by AGENT404TRD** [comment]
We removed it a while ago.

**Comment by ryangp** [comment]
> We removed it a while ago.

when are you going to put it back sir?
